---
title: "Support Vector Machine"
output: html_notebook
---

https://www.geeksforgeeks.org/classifying-data-using-support-vector-machinessvms-in-r/
_Introduction to Statisitcal learning with Applications in R_, James, Witten, Hastie, Tibshirani
* pg 359
# Loading Data
```{r}
library(caTools) 
library(e1071)
library(dplyr)
```

```{r}
train <- read.csv('../data/processed/ebird_split_train.csv')
train <- train %>% select(-X)
test <- read.csv('../data/processed/ebird_split_test.csv')
# test <- test %>% select(-X)
names(train)
train[2]
```

# Scaling features
```{r}
# Feature Scaling 
train
train <- train %>% mutate_at(-c(1), scale)
test <- test %>% mutate_at(-c(1), scale)
```

# Linear svm
## Cost of 1
```{r}
classifier <- svm(formula = species_observed ~ ., 
                 data = train, 
                 type = 'C-classification', 
                 kernel = 'linear')
classifier
```
```{r}
summary(classifier)
```
```{r}
select(test, -c(1))

classifier
y_pred <- predict(classifier, newdata = select(test, -c(1))) 
head(y_pred)

names(test[, 3])
# Making the Confusion Matrix 
nrow(y_pred)
nrow(test$species_observed)

confusion_matrix <- table(test$species_observed, y_pred) 
confusion_matrix
```

```{r}
3298/(3298+ 2108)
```

```{r}
3495/(3495+1235)
```

## Tune to determine the optimal cost parameter

```{r}
set.sed(1)
tune.out = tune(svm, formula = species_observed ~ ., 
                 data = train, 
                 type = 'C-classification', 
                 kernel = 'linear',
                ranges = list(cost = c(.001,)))
```